meta_data_format_example = """
Below is an example of Metadata that you need to create for the given information above
{
  "metadata": {
    "document_info": {
      "id": "steel-sector-report-june-2024",
      "title": "India turns net steel importer; domestic demand a bright spot",
      "author": "CRISIL MI&A Research",
      "date_published": "2024-06-20",
      "source": "CRISIL Market Intelligence & Analytics",
      "document_type": "sector_update"
    },
    "content_classification": {
      "macro_economic_sector": "Commodities",
      "sector": "Metals & Mining",
      "industry": "Ferrous Metals",
      "basic_industry": "Iron & Steel",
      "topics": [
        "steel_imports_exports",
        "global_steel_trade",
        "domestic_steel_demand",
        "environmental_regulations"
      ]
    },
    "market_analysis": {
      "key_data": {
        "steel_trade_deficit_FY2024": "1.1 million tonnes",
        "finished_steel_imports_FY2024": "8.3 million tonnes",
        "finished_steel_exports_FY2024": "7.5 million tonnes",
        "steel_consumption_growth_FY2024": "13.6%"
      },
      "key_players": [
        "Tata Steel",
        "JSW Steel",
        "Steel Authority of India Limited (SAIL)",
        "Jindal Steel and Power Limited",
        "ArcelorMittal Nippon Steel India"
      ],
      "key_demand_drivers": [
        "Infrastructure development",
        "Automotive industry",
        "Construction sector",
        "Manufacturing growth",
        "Government initiatives"
      ]
    },
    "risk_factors": {
      "market_risks": [
        "Weak global markets",
        "Competitive Chinese steel",
        "EU's Carbon Border Adjustment Mechanism (CBAM)",
        "Fluctuating raw material prices",
        "Currency exchange rate volatility",
        "Global economic slowdown"
      ],
      "operational_risks": [
        "Adapting to low-carbon technologies",
        "Supply chain disruptions",
        "Labor shortages or disputes"
      ],
      "climate_risks": [],
      "regulatory_risks": [
        "Changes in import/export policies",
        "Environmental regulations tightening",
        "Trade barriers or tariffs"
      ]
    },
    "future_outlook": {
      "growth_projections": {
        "Additional capacity for specialty steel by FY2028": "25 million tonnes"
      },
      "emerging_trends": [
        "Increasing domestic steel consumption",
        "Adoption of best available technologies for emission reduction"
      ],
      "potential_disruptions": [
        "Technological advancements in steel production",
        "Shift towards green steel",
        "Changes in global trade policies"
      ]
    },
    "government_policies": {
      "policy_name": "Production-Linked Incentive (PLI) scheme",
      "policy_type": "Investment incentive",
      "description": "Promoting production of specialty grade steel in India between fiscals 2024 and 2030"
    }
  }
}"""

#put all the data for required constraints
document_type_constraint = """
  "document_type" key in "document_info" key can only include values inside this list [
    "sector_update",
    "market_analysis",
    "economic_outlook",
    "industry_overview",
    "research_note",
    "policy_brief",
    "risk_assessment",
    "regulatory_filing",
    "white_paper"
  ]"""
macro_economic_sectors_constraint = """
  "macro_economic_sector" in "content_classification" key only include values inside this list [
    "Commodities",
    "Consumer Discretionary",
    "Energy",
    "Fast Moving Consumer Goods",
    "Financial Services",
    "Healthcare",
    "Industrials",
    "Information Technology",
    "Services",
    "Telecommunication",
    "Utilities",
    "Diversified"
  ]"""
sectors_constraint = """
  "sector" in "content_classification" key only include values inside this list[
    "Chemicals",
    "Construction Materials",
    "Metals & Mining",
    "Forest Materials",
    "Automobile and Auto Components",
    "Consumer Durables",
    "Textiles",
    "Media, Entertainment & Publication",
    "Realty",
    "Consumer Services",
    "Oil, Gas & Consumable Fuels",
    "Fast Moving Consumer Goods",
    "Financial Services",
    "Healthcare",
    "Construction",
    "Capital Goods",
    "Information Technology",
    "Services",
    "Telecommunication",
    "Power",
    "Utilities",
    "Diversified"
  ]"""

industries_constraint= """
  "industry" in "content_classification" key only include values inside this list: [
    "Chemicals & Petrochemicals",
    "Fertilizers & Agrochemicals",
    "Cement & Cement Products",
    "Other Construction Materials",
    "Ferrous Metals",
    "Non - Ferrous Metals",
    "Diversified Metals",
    "Minerals & Mining",
    "Metals & Minerals Trading",
    "Paper, Forest & Jute Products",
    "Automobiles",
    "Auto Components",
    "Consumer Durables",
    "Textiles & Apparels",
    "Media",
    "Entertainment",
    "Printing & Publication",
    "Realty",
    "Leisure Services",
    "Other Consumer Services",
    "Retailing",
    "Gas",
    "Oil",
    "Petroleum Products",
    "Consumable Fuels",
    "Agricultural Food & other Products",
    "Beverages",
    "Cigarettes & Tobacco Products",
    "Food Products",
    "Personal Products",
    "Household Products",
    "Diversified FMCG",
    "Finance",
    "Banks",
    "Capital Markets",
    "Insurance",
    "Financial Technology (Fintech)",
    "Pharmaceuticals & Biotechnology",
    "Healthcare Equipment & Supplies",
    "Healthcare Services",
    "Construction",
    "Aerospace & Defense",
    "Agricultural, Commercial & Construction Vehicles",
    "Electrical Equipment",
    "Industrial Manufacturing",
    "Industrial Products",
    "IT - Software",
    "IT - Services",
    "IT - Hardware",
    "Engineering Services",
    "Transport Services",
    "Transport Infrastructure",
    "Commercial Services & Supplies",
    "Public Services",
    "Telecom - Services",
    "Telecom - Equipment & Accessories",
    "Power",
    "Other Utilities",
    "Diversified"
  ]"""

basic_industries_constraint="""
  "basic_industry" inside "content_classification" key only include values inside this list [
    "Commodity Chemicals",
    "Specialty Chemicals",
    "Carbon Black",
    "Dyes And Pigments",
    "Explosives",
    "Petrochemicals",
    "Printing Inks",
    "Trading - Chemicals",
    "Industrial Gases",
    "Fertilizers",
    "Pesticides & Agrochemicals",
    "Cement & Cement Products",
    "Other Construction Materials",
    "Ferro & Silica Manganese",
    "Pig Iron",
    "Sponge Iron",
    "Iron & Steel",
    "Aluminium",
    "Copper",
    "Zinc",
    "Precious Metals",
    "Diversified Metals",
    "Industrial Minerals",
    "Trading - Metals",
    "Trading - Minerals",
    "Paper & Paper Products",
    "Forest Products",
    "Jute & Jute Products",
    "Passenger Cars & Utility Vehicles",
    "2/3 Wheelers",
    "Auto Dealer",
    "Auto Components & Equipments",
    "Tyres & Rubber Products",
    "Trading - Auto Components",
    "Cycles",
    "Consumer Electronics",
    "Gems, Jewellery And Watches",
    "Glass - Consumer",
    "Household Appliances",
    "Houseware",
    "Leather And Leather Products",
    "Leisure Products",
    "Plastic Products - Consumer",
    "Plywood Boards/ Laminates",
    "Sanitary Ware",
    "Paints",
    "Diversified consumer products",
    "Footwear",
    "Furniture, Home Furnishing",
    "Ceramics",
    "Granites & Marbles",
    "Garments & Apparels",
    "Other Textile Products",
    "Trading - Textile Products",
    "Advertising & Media Agencies",
    "Electronic Media",
    "Web based media and service",
    "Print Media",
    "Film Production, Distribution & Exhibition",
    "Digital Entertainment",
    "Media & Entertainment",
    "TV Broadcasting & Software Production",
    "Printing & Publication",
    "Residential, Commercial Projects",
    "Real Estate related services",
    "Real Estate Investment Trusts (REITs)",
    "Hotels & Resorts",
    "Restaurants",
    "Amusement Parks/ Other Recreation",
    "Wellness",
    "Tour, Travel Related Services",
    "Education",
    "E-Learning",
    "Food Storage Facilities",
    "Other Consumer Services",
    "Speciality Retail",
    "Pharmacy Retail",
    "Diversified Retail",
    "E-Retail/ E-Commerce",
    "Internet & Catalogue Retail",
    "Distributors",
    "Gas Transmission/Marketing",
    "LPG/CNG/PNG/LNG Supplier",
    "Trading - Gas",
    "Oil Exploration & Production",
    "Offshore Support Solution Drilling",
    "Oil Storage & Transportation",
    "Oil Equipment & Services",
    "Refineries & Marketing",
    "Lubricants",
    "Coal",
    "Trading - Coal",
    "Edible Oil",
    "Sugar",
    "Tea & Coffee",
    "Other Agricultural Products",
    "Breweries & Distilleries",
    "Other Beverages",
    "Cigarettes & Tobacco Products",
    "Animal Feed",
    "Dairy Products",
    "Other Food Products",
    "Packaged Foods",
    "Seafood",
    "Meat Products including Poultry",
    "Personal Care",
    "Household Products",
    "Stationary",
    "Diversified FMCG",
    "Financial Institution",
    "Housing Finance Company",
    "Investment Company",
    "Non Banking Financial Company (NBFC)",
    "Other Financial Services",
    "Holding Company",
    "Microfinance Institutions",
    "Securitisation",
    "Public Sector Bank",
    "Private Sector Bank",
    "Other Bank",
    "Asset Management Company",
    "Depositories, Clearing Houses and Other Intermediaries",
    "Financial Products Distributor",
    "Ratings",
    "Exchange and Data Platform",
    "Stockbroking & Allied",
    "Other Capital Market related Services",
    "General Insurance",
    "Life Insurance",
    "Other Insurance Companies",
    "Insurance Distributors",
    "Financial Technology (Fintech)",
    "Pharmaceuticals",
    "Biotechnology",
    "Medical Equipment & Supplies",
    "Hospital",
    "Healthcare Service Provider",
    "Healthcare Research, Analytics & Technology",
    "Civil Construction",
    "Aerospace & Defense",
    "Tractors",
    "Commercial Vehicles",
    "Construction Vehicles",
    "Dealers– Commercial Vehicles, Tractors, Construction Vehicles",
    "Heavy Electrical Equipment",
    "Other Electrical Equipment",
    "Railway Wagons",
    "Ship Building & Allied Services",
    "Industrial Products",
    "Cables - Electricals",
    "Castings & Forgings",
    "Packaging",
    "Plastic Products - Industrial",
    "Rubber",
    "Other Industrial Products",
    "Glass - Industrial",
    "Aluminium, Copper & Zinc Products",
    "Iron & Steel Products",
    "Abrasives & Bearings",
    "Compressors, Pumps & Diesel Engines",
    "Electrodes & Refractories",
    "Computers - Software & Consulting",
    "Software Products",
    "IT Enabled Services",
    "Computers Hardware & Equipments",
    "Dredging",
    "Airline",
    "Logistics Solution Provider",
    "Railways",
    "Road Transport",
    "Shipping",
    "Transport Related Services",
    "Airport & Airport services",
    "Port & Port services",
    "Road Assets–Toll, Annuity, Hybrid-Annuity",
    "Trading & Distributors",
    "Consulting Services",
    "Data Processing Services",
    "Diversified Commercial Services",
    "Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)",
    "Urban Local Bodies",
    "Development Authority",
    "Telecom - Cellular & Fixed line services",
    "Telecom - Infrastructure",
    "Other Telecom Services",
    "Telecom - Equipment & Accessories",
    "Power Trading",
    "Power - Transmission",
    "Power Generation",
    "Integrated Power Utilities",
    "Power Distribution",
    "Water Supply & Management",
    "Waste Management",
    "Emergency Services",
    "Multi Utilities",
    "Other Utilities",
    "Diversified"
  ]"""
